name: Build and Publish .NET App

on:
  workflow_dispatch:
    inputs:
      build-docker:
        description: 'Build and push Docker image'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./MiNotSoSimpleApp/MiNotSoSimpleApp.csproj

      - name: Build
        run: dotnet build ./MiNotSoSimpleApp/MiNotSoSimpleApp.csproj --configuration Release

      - name: Test
        run: dotnet test ./MiNotSoSimpleAppTests/MiNotSoSimpleAppTests.csproj --configuration Release

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest ./MiNotSoSimpleApp
          docker push your-dockerhub-username/your-image-name:latest
        env:
          DOCKER_CLI_ACI: 1
